project:
  type: website
  output-dir: docs

website:
  title: "Mingxin Liu"
  
  navbar:
    left:
      - text: "Research"
        file: Research.qmd
      - text: "Publications"
        file: Publications.qmd
      - text: "Blogs"
        file: Blogs.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
